# [general]
# import = [
#   "~/.config/alacritty/tokyo_night_enhanced.toml",
# ]

[font]
size = 16

[font.normal]
# family = "Iosevka Nerd Font"
# family = "JetBrainsMono Nerd Font"
# family = "Terminess Nerd Font"
family = "Zed Mono Nerd Font"
style = "Regular"

# [font.italic]
# style = "Medium Oblique"

[font.offset]
y = 0

[font.glyph_offset]
y = 0

[scrolling]
history = 10000

[window]
opacity = 1
startup_mode = "Maximized"
option_as_alt = "Both"
